datasets:
  cifar100:
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      splits: ["val"]
      images:
          storage: /work/users/y/l/ylsung/data/
